// Autogenerated from Pigeon (v10.1.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum AccountType {
  defaultUnspecified,
  savings,
  current,
  credit,
  universal,
  investment,
}

enum Environment {
  live,
  test,
}

class TransactionDataResponse {
  TransactionDataResponse({
    this.amount,
    this.deviceState,
    this.authorizationCode,
    this.cardExpiryDate,
    this.cardHolderName,
    this.date,
    this.maskedPan,
    this.merchantId,
    this.merchantName,
    this.responseCode,
    this.responseMessage,
    this.rrn,
    this.stan,
    this.terminalId,
    this.transactionType,
    this.isSuccessful,
  });

  String? amount;

  String? deviceState;

  String? authorizationCode;

  String? cardExpiryDate;

  String? cardHolderName;

  String? date;

  String? maskedPan;

  String? merchantId;

  String? merchantName;

  String? responseCode;

  String? responseMessage;

  String? rrn;

  String? stan;

  String? terminalId;

  String? transactionType;

  bool? isSuccessful;

  Object encode() {
    return <Object?>[
      amount,
      deviceState,
      authorizationCode,
      cardExpiryDate,
      cardHolderName,
      date,
      maskedPan,
      merchantId,
      merchantName,
      responseCode,
      responseMessage,
      rrn,
      stan,
      terminalId,
      transactionType,
      isSuccessful,
    ];
  }

  static TransactionDataResponse decode(Object result) {
    result as List<Object?>;
    return TransactionDataResponse(
      amount: result[0] as String?,
      deviceState: result[1] as String?,
      authorizationCode: result[2] as String?,
      cardExpiryDate: result[3] as String?,
      cardHolderName: result[4] as String?,
      date: result[5] as String?,
      maskedPan: result[6] as String?,
      merchantId: result[7] as String?,
      merchantName: result[8] as String?,
      responseCode: result[9] as String?,
      responseMessage: result[10] as String?,
      rrn: result[11] as String?,
      stan: result[12] as String?,
      terminalId: result[13] as String?,
      transactionType: result[14] as String?,
      isSuccessful: result[15] as bool?,
    );
  }
}

class CardDetails {
  CardDetails({
    this.primaryAccountNumber,
    this.track1,
    this.track2,
    this.expiryDate,
    this.serviceCode,
    this.iccCardData,
    this.cardSequenceNumber,
    this.pinBlock,
    this.cardSlotTypeEnum,
    this.cardHolderName,
  });

  String? primaryAccountNumber;

  String? track1;

  String? track2;

  String? expiryDate;

  String? serviceCode;

  String? iccCardData;

  String? cardSequenceNumber;

  String? pinBlock;

  String? cardSlotTypeEnum;

  String? cardHolderName;

  Object encode() {
    return <Object?>[
      primaryAccountNumber,
      track1,
      track2,
      expiryDate,
      serviceCode,
      iccCardData,
      cardSequenceNumber,
      pinBlock,
      cardSlotTypeEnum,
      cardHolderName,
    ];
  }

  static CardDetails decode(Object result) {
    result as List<Object?>;
    return CardDetails(
      primaryAccountNumber: result[0] as String?,
      track1: result[1] as String?,
      track2: result[2] as String?,
      expiryDate: result[3] as String?,
      serviceCode: result[4] as String?,
      iccCardData: result[5] as String?,
      cardSequenceNumber: result[6] as String?,
      pinBlock: result[7] as String?,
      cardSlotTypeEnum: result[8] as String?,
      cardHolderName: result[9] as String?,
    );
  }
}

class _LibertyEmvApiCodec extends StandardMessageCodec {
  const _LibertyEmvApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CardDetails) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is TransactionDataResponse) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return CardDetails.decode(readValue(buffer)!);
      case 129: 
        return TransactionDataResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LibertyEmvApi {
  /// Constructor for [LibertyEmvApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LibertyEmvApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _LibertyEmvApiCodec();

  Future<TransactionDataResponse> initialise(Environment arg_environment) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LibertyEmvApi.initialise', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_environment.index]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TransactionDataResponse?)!;
    }
  }

  Future<TransactionDataResponse> enquireBalance(bool arg_isOfflineTransaction, AccountType arg_accountType, String arg_rrn) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LibertyEmvApi.enquireBalance', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_isOfflineTransaction, arg_accountType.index, arg_rrn]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TransactionDataResponse?)!;
    }
  }

  Future<TransactionDataResponse> purchase(String arg_amount, AccountType arg_accountType, String arg_rrn) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LibertyEmvApi.purchase', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_amount, arg_accountType.index, arg_rrn]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TransactionDataResponse?)!;
    }
  }

  Future<TransactionDataResponse> performKeyExchange() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LibertyEmvApi.performKeyExchange', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TransactionDataResponse?)!;
    }
  }

  Future<TransactionDataResponse> print(Uint8List arg_bitmap) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LibertyEmvApi.print', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_bitmap]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TransactionDataResponse?)!;
    }
  }

  Future<CardDetails?> getCardDetails() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LibertyEmvApi.getCardDetails', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return (replyList[0] as CardDetails?);
    }
  }

  Future<void> launchAppStore() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.LibertyEmvApi.launchAppStore', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}
