// Autogenerated from Pigeon (v7.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class KeyExchangeResponse {
  KeyExchangeResponse({
    this.deviceState,
    this.isSuccessful,
  });

  String? deviceState;

  bool? isSuccessful;

  Object encode() {
    return <Object?>[
      deviceState,
      isSuccessful,
    ];
  }

  static KeyExchangeResponse decode(Object result) {
    result as List<Object?>;
    return KeyExchangeResponse(
      deviceState: result[0] as String?,
      isSuccessful: result[1] as bool?,
    );
  }
}

class TransactionDataResponse {
  TransactionDataResponse({
    this.amount,
    this.deviceState,
    this.authorizationCode,
    this.cardExpiryDate,
    this.cardHolderName,
    this.date,
    this.maskedPan,
    this.merchantId,
    this.merchantName,
    this.responseCode,
    this.responseMessage,
    this.rrn,
    this.stan,
    this.terminalId,
    this.transactionType,
  });

  String? amount;

  String? deviceState;

  String? authorizationCode;

  String? cardExpiryDate;

  String? cardHolderName;

  String? date;

  String? maskedPan;

  String? merchantId;

  String? merchantName;

  String? responseCode;

  String? responseMessage;

  String? rrn;

  String? stan;

  String? terminalId;

  String? transactionType;

  Object encode() {
    return <Object?>[
      amount,
      deviceState,
      authorizationCode,
      cardExpiryDate,
      cardHolderName,
      date,
      maskedPan,
      merchantId,
      merchantName,
      responseCode,
      responseMessage,
      rrn,
      stan,
      terminalId,
      transactionType,
    ];
  }

  static TransactionDataResponse decode(Object result) {
    result as List<Object?>;
    return TransactionDataResponse(
      amount: result[0] as String?,
      deviceState: result[1] as String?,
      authorizationCode: result[2] as String?,
      cardExpiryDate: result[3] as String?,
      cardHolderName: result[4] as String?,
      date: result[5] as String?,
      maskedPan: result[6] as String?,
      merchantId: result[7] as String?,
      merchantName: result[8] as String?,
      responseCode: result[9] as String?,
      responseMessage: result[10] as String?,
      rrn: result[11] as String?,
      stan: result[12] as String?,
      terminalId: result[13] as String?,
      transactionType: result[14] as String?,
    );
  }
}

class _EmvApiCodec extends StandardMessageCodec {
  const _EmvApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is KeyExchangeResponse) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is TransactionDataResponse) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return KeyExchangeResponse.decode(readValue(buffer)!);
      case 129: 
        return TransactionDataResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class EmvApi {
  /// Constructor for [EmvApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EmvApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _EmvApiCodec();

  Future<TransactionDataResponse> enquireBalance(String arg_tID, String arg_accountType) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.EmvApi.enquireBalance', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_tID, arg_accountType]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TransactionDataResponse?)!;
    }
  }

  Future<TransactionDataResponse> purchase(String arg_amount, String arg_accountType) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.EmvApi.purchase', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_amount, arg_accountType]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as TransactionDataResponse?)!;
    }
  }

  Future<KeyExchangeResponse> performKeyExchange() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.EmvApi.performKeyExchange', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as KeyExchangeResponse?)!;
    }
  }
}
